# gobazel eventtest
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: gobazel-eventtest
  labels:
    app: gobazel
    component: eventtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gobazel
      component: eventtest
  template:
    metadata:
      labels:
        app: gobazel
        component: eventtest
    spec:
      containers:
      - name: eventtest
        image: localhost:5000/gobazel-eventtest:dev
        args: ["--debug"]
        ports:
        - containerPort: 8080
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: eventtest
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "9090"
spec:
  selector:
    app: gobazel
    component: eventtest
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: metrics
    port: 9090
    targetPort: 9090
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: eventtest
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: gobazel.k8s
    http:
      paths:
        - path: /eventtest
          backend:
            serviceName: eventtest
            servicePort: http
