# gobazel service 2
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: gobazel-greet
  labels:
    app: gobazel
    component: greet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gobazel
      component: greet
  template:
    metadata:
      labels:
        app: gobazel
        component: greet
    spec:
      containers:
      - name: greet
        image: localhost:5000/gobazel-greet:dev
        ports:
        - containerPort: 8080
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: greet
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "9090"
spec:
  selector:
    app: gobazel
    component: greet
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: metrics
    port: 9090
    targetPort: 9090
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: greet
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: gobazel.minikube
    http:
      paths:
        - path: /greet
          backend:
            serviceName: greet
            servicePort: http
        # - path: /another
        #   backend:
        #     serviceName: another
        #     servicePort: http