# gobazel launcher service
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: gobazel-launcher
  labels:
    app: gobazel
    component: launcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gobazel
      component: launcher
  template:
    metadata:
      labels:
        app: gobazel
        component: launcher
    spec:
      containers:
      - name: launcher
        image: localhost:5000/gobazel-launcher:dev
        ports:
        - containerPort: 8080
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: launcher
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "9090"
spec:
  selector:
    app: gobazel
    component: launcher
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: metrics
    port: 9090
    targetPort: 9090
