// Code generated by protoc-gen-go. DO NOT EDIT.
// source: greeting.proto

/*
Package protos is a generated protocol buffer package.

It is generated from these files:
	greeting.proto

It has these top-level messages:
	GreetingResponse
	Empty
*/
package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GreetingResponse struct {
	Greeting string `protobuf:"bytes,1,opt,name=Greeting" json:"Greeting,omitempty"`
	Err      string `protobuf:"bytes,2,opt,name=Err" json:"Err,omitempty"`
}

func (m *GreetingResponse) Reset()                    { *m = GreetingResponse{} }
func (m *GreetingResponse) String() string            { return proto.CompactTextString(m) }
func (*GreetingResponse) ProtoMessage()               {}
func (*GreetingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GreetingResponse) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

func (m *GreetingResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*GreetingResponse)(nil), "protos.GreetingResponse")
	proto.RegisterType((*Empty)(nil), "protos.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Greeting service

type GreetingClient interface {
	Greeting(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GreetingResponse, error)
}

type greetingClient struct {
	cc *grpc.ClientConn
}

func NewGreetingClient(cc *grpc.ClientConn) GreetingClient {
	return &greetingClient{cc}
}

func (c *greetingClient) Greeting(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GreetingResponse, error) {
	out := new(GreetingResponse)
	err := grpc.Invoke(ctx, "/protos.Greeting/Greeting", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Greeting service

type GreetingServer interface {
	Greeting(context.Context, *Empty) (*GreetingResponse, error)
}

func RegisterGreetingServer(s *grpc.Server, srv GreetingServer) {
	s.RegisterService(&_Greeting_serviceDesc, srv)
}

func _Greeting_Greeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreetingServer).Greeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Greeting/Greeting",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreetingServer).Greeting(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeting_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.Greeting",
	HandlerType: (*GreetingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Greeting",
			Handler:    _Greeting_Greeting_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "greeting.proto",
}

func init() { proto.RegisterFile("greeting.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 121 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0x2f, 0x4a, 0x4d,
	0x2d, 0xc9, 0xcc, 0x4b, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x03, 0x53, 0xc5, 0x4a,
	0x0e, 0x5c, 0x02, 0xee, 0x50, 0x99, 0xa0, 0xd4, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x29,
	0x2e, 0x0e, 0x98, 0x98, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x9c, 0x2f, 0x24, 0xc0, 0xc5,
	0xec, 0x5a, 0x54, 0x24, 0xc1, 0x04, 0x16, 0x06, 0x31, 0x95, 0xd8, 0xb9, 0x58, 0x5d, 0x73, 0x0b,
	0x4a, 0x2a, 0x8d, 0xec, 0x11, 0xda, 0x84, 0x8c, 0x91, 0xd8, 0xbc, 0x10, 0x2b, 0x8b, 0xf5, 0xc0,
	0xca, 0xa4, 0x24, 0x60, 0x5c, 0x74, 0x7b, 0x93, 0x20, 0x6e, 0x32, 0x06, 0x04, 0x00, 0x00, 0xff,
	0xff, 0x3f, 0x68, 0xf1, 0x22, 0xac, 0x00, 0x00, 0x00,
}
