apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: registry-backend
  labels:
    app: gobazel
    component: registry-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gobazel
      component: registry-backend
  template:
    metadata:
      labels:
        app: gobazel
        component: registry-backend
    spec:
      containers:
      - name: registry-backend
        image: registry:2.6.2
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: REGISTRY_HTTP_ADDR
          value: :5000
        ports:
        - containerPort: 5000
          protocol: TCP
          name: registry
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gobazel
    component: registry
  name: registry
spec:
  selector:
    app: gobazel
    component: registry-backend
  ports:
  - name: registry
    protocol: TCP
    port: 5000
---
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: registry-in
#   labels:
#     app: gobazel
#     component: registry-in
#   annotations:
#     kubernetes.io/ingress.class: traefik
# spec:
#   rules:
#   - host: minikube
#     http:
#       paths:
#         - path: /
#           backend:
#             serviceName: registry
#             servicePort: registry
# ---
apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: registry-proxy
  labels:
    app: gobazel
    component: registry-proxy
spec:
  selector:
    matchLabels:
      app: gobazel
      component: registry-proxy
  template:
    metadata:
      labels:
        app: gobazel
        component: registry-proxy
    spec:
      containers:
      - name: registry-proxy
        image: gcr.io/google_containers/kube-registry-proxy:0.4
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
        env:
        - name: REGISTRY_HOST
          value: registry.gobazel.svc.cluster.local
        - name: REGISTRY_PORT
          value: "5000"
        ports:
        - name: registry
          containerPort: 80
          hostPort: 5000
